language: java
jdk:
  - openjdk6
cache:
  directories:
  - $HOME/.m2
install: "mvn install -s .maven_settings.xml -DskipTests=true -Dmaven.javadoc.skip=true -B"
script: "mvn test -s .maven_settings.xml -Dmaven.javadoc.skip=true -B"
after_success: "mvn deploy -s .maven_settings.xml -DskipTests=true -B"
